<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>       
        <div class="container">
            <br><br>
            <div class="row">
                <div class="panel panel-info">
                    <div class="panel-heading">Cambiar Clave Usuario</div>
                    <div class="panel-body">
                        <form class="form-horizontal text-center" action="" method="post">
                            <?php
                            if((isset($_GET['m']))and($_GET['m'] == 1))
                            {
                                echo '<div class="alert alert-danger" role="alert"><p>La clave actual es incorrecta, porfavor intente denuevo</p></div>';
                            }
                            ?>
                            <div class="form-group">                                
                                <label class="control-label col-xs-12 col-sm-2">Clave Actual</label>
                                <div class="col-xs-12 col-sm-4">
                                    <input id="claveactual" class="form-control" name="claveactual" type="password" placeholder="Clave Actual" required>
                                </div>                                
                            </div>
                            <?php 
                            if((isset($_GET['m']))and($_GET['m'] == 2))
                            {
                                echo '<div class="alert alert-danger" role="alert"><p>Los Campos de la nueva contraseña deben coincidir</p></div>';
                            }
                            ?>
                            
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Clave Nueva</label>
                                <div class="col-sm-4">
                                    <input id="nueva1" name="nueva1" class="form-control" type="password" placeholder="Clave Nueva" required>
                                </div>                               
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Repetir Clave Nueva</label>
                                <div class="col-sm-4">
                                    <input id="nueva2" name="nueva2" class="form-control" type="password" placeholder="Repetir Clave Nueva" required>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-1">
                                    <button type="submit" class="btn btn-primary" value="si" name="envioclave" title="Cambiar Clave" id="cambiaclave">&nbsp;<span class="glyphicon glyphicon-new-window"></span>&nbsp;</button>
                                </div>
                            </div>
                        </form>              
                    </div>
                </div>
            </div>
        </div>        
        <?php include 'core/inc/footer_index.php'?>
        <script src="style/js/familiar_sa.js" type="text/javascript"></script>
    </body>
</html>
