<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        <?php include 'core/inc/header_admin.php' ?>
        <div class="container">
            <div class="row">
                <div class="panel panel-info">
                    <div class="panel-heading">Crear Cuota</div>
                    <div class="panel-body">
                        <form class="form-horizontal" action="" onsubmit="add_cuota(); return false">
                            <div class="form-group">                                
                                <label class="col-sm-2 col-md-1 control-label">Nombre Cuota</label>
                                <div class="col-sm-3 col-md-4">
                                    <input id="ccs_nombre" class="form-control" type="text" placeholder="Nombre Cuota" required>
                                </div>
                                <label class="col-sm-2 col-md-1 control-label">Descripción</label>
                                <div class="col-sm-4 col-md-4">
                                    <input id="ccs_descripcion" class="form-control" type="text" placeholder="Descripción" required>
                                </div>                                
                            </div>
                            <div class="form-group">
                                <label class="col-sm-1 control-label">Valor S.A</label>
                                <div class="col-sm-3 col-md-2">
                                    <input id="ccs_valorsa" class="form-control" type="number" placeholder="Valor S.A" required >
                                </div>                                                                
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-1 col-md-offset-1 col-sm-1">
                                    <button type="submit" class="btn btn-primary" title="Agregar" id="ccs_agregar">&nbsp;<span class="glyphicon glyphicon-floppy-disk"></span>&nbsp;</button>
                                </div>
                            </div>
                        </form>               
                        <br>
                        <br>
                        <table class="table table-striped display" id="ccs_tabla">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Nombre</th>                                    
                                    <th>Fecha</th>
                                </tr>
                            </thead>
                            <tbody id="ccs_tbody">
                                
                            </tbody>                                                                                       
                        </table>
                    </div>
                </div>
            </div>
        </div>     
        <?php include 'core/view/modal_cuotas.php'?>
        <?php include 'core/inc/footer_index.php'?>
        <script src="/style/js/crear_cuota.js" type="text/javascript"></script>
    </body>
</html>
