<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        <?php include 'core/inc/header_admin.php' ?>
        <div class="container">
            <div class="row">
                <div class="panel panel-info">
                    <div class="panel-heading">Familiar Socio Transeunte</div>
                    <div class="panel-body">
                        <form class="form-horizontal" action="" onsubmit="busca_sactivo(); return false">
                            <div class="form-group">
                                <div class="col-sm-1 col-md-1">
                                    <button type="button" class="btn btn-primary" title="Buscar" id="fst_buscar"><span class="glyphicon glyphicon-search"></span></button>
                                </div>
                                <label class="col-sm-1 control-label">Rut</label>
                                <div class="col-sm-2 col-md-2">
                                    <input id="st_rut" class="form-control" type="text" placeholder="Rut" required disabled>
                                </div>
                                <label class="col-sm-1 control-label">Nombres</label>
                                <div class="col-sm-6 col-md-6">
                                    <input id="st_nombres" class="form-control" type="text" placeholder="Nombres" required disabled>
                                </div>
                                <div class="col-sm-1">
                                    <button type="button" class="btn btn-primary" title="Agregar" id="fst_agregar">&nbsp;<span class="glyphicon glyphicon-new-window"></span>&nbsp;</button>
                                </div>
                            </div>
                        </form>               
                        <br>
                        <br>
                        <table class="table table-striped display" id="fst_tabla">
                            <thead>
                                <tr>
                                    <th>Rut</th>
                                    <th>Nombre</th>                        
                                </tr>
                            </thead>
                            <tbody id="fst_tbody">
                                
                            </tbody>                                                                                           
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <?php include 'core/view/modal_sa_buscar.php'?>
        <?php include 'core/view/modal_agregar.php'?>
        <?php include 'core/inc/footer_index.php'?>
        <script src="style/js/familiar_st.js" type="text/javascript"></script>
    </body>
</html>
