<header>
    <nav class="navbar navbar-default navbar-static-top navbar-inverse" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-login-1">
                    <span class="sr-only">Menú</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="#" class="navbar-brand">Login</a>
            </div>
            <div class="collapse navbar-collapse" id="navbar-login-1">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="<?php Config::ruta();?>?accion=loginusuario">Login Usuarios<span class="sr-only"></span></a>
                    </li>                
                    <li>
                        <a href="<?php Config::ruta();?>?accion=loginadmin">Login Administrador</a>
                    </li>
                </ul>           
            </div>             
        </div>
    </nav>
</header>

