<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        <?php include 'core/inc/header_admin.php' ?>
        <div class="container">
            <div class="row">
                <div class="panel panel-info">
                    <div class="panel-heading">Ingreso Competencias</div>
                    <div class="panel-body">
                        <form class="form-horizontal" action="" onsubmit="add_competencia(); return false">
                            <div class="form-group">                                
                                <label class="col-sm-2 col-md-1 control-label">Descripción</label>
                                <div class="col-sm-5 col-md-5">
                                    <input id="ic_descripcion" class="form-control" type="text" placeholder="Descripción" required>
                                </div>
                                <label class="col-sm-2 col-md-1 control-label">Edad Minima</label>
                                <div class="col-sm-3 col-md-2">
                                    <input id="ic_edadminima" class="form-control" type="number" placeholder="Edad Minima" required >
                                </div>                               
                                <label class="col-sm-2 col-md-1 control-label">Edad Maxima</label>
                                <div class="col-sm-3 col-md-2">
                                    <input id="ic_edadmaxima" class="form-control" type="number" placeholder="Edad Maxima" required >
                                </div>                               
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 col-md-1 control-label">Cupos</label>
                                <div class="col-sm-3 col-md-2">
                                    <input id="ic_cupos" class="form-control" type="number" placeholder="Cupos" required >
                                </div>
                                <label class="col-sm-2 col-md-1 control-label">Fecha</label>
                                <div class="col-sm-3 col-md-3">
                                    <input id="ic_fecha" class="form-control" type="date" placeholder="Fecha" required >
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-2">
                                    <button type="submit" class="btn btn-primary" title="Agregar" id="ic_agregar">&nbsp;<span class="glyphicon glyphicon-floppy-disk"></span>&nbsp;</button>
                                    <button type="button" class="btn btn-primary invi" title="Editar" id="ic_editar">&nbsp;<span class="glyphicon glyphicon-edit"></span>&nbsp;</button>
                                    <button type="button" class="btn btn-danger invi" title="Cancelar" id="ic_cancelar">&nbsp;<span class="glyphicon glyphicon-erase"></span>&nbsp;</button>
                                </div>
                            </div>
                        </form>               
                        <br>
                        <br>
                        <table class="table table-striped display" id="ic_tabla">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Descripción</th>
                                    <th>Fecha</th>                                    
                                </tr>
                            </thead>
                            <tbody id="ic_tbody">
                                
                            </tbody>                                                                                          
                        </table>
                    </div>
                </div>
            </div>
        </div>        
        <?php include 'core/inc/footer_index.php'?>
        <script src="/style/js/ingreso_competencias.js" type="text/javascript"></script>
    </body>
</html>
