<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        <?php include 'core/inc/header_admin.php' ?>
        <div class="container">
            <div class="row">
                <div class="panel panel-info">
                    <div class="panel-heading">Ingreso Canchas</div>
                    <div class="panel-body">
                        <form class="form-horizontal" action="" onsubmit="add_curso(); return false">
                            <div class="form-group">                                
                                <label class="col-sm-2 col-md-1 control-label">Descripción</label>
                                <div class="col-sm-3 col-md-4">
                                    <input id="icu_descripcion" class="form-control" type="text" placeholder="Descripción" required>
                                </div>
                                <label class="col-sm-2 col-md-1 control-label">Profesor</label>
                                <div class="col-sm-4 col-md-4">
                                    <input id="icu_profesor" class="form-control" type="text" placeholder="Profesor" required>
                                </div>                                
                            </div>
                            <div class="form-group">
                                <label class="col-sm-1 control-label">Valor S.A</label>
                                <div class="col-sm-3 col-md-2">
                                    <input id="icu_valorsa" class="form-control" type="number" placeholder="Valor S.A" required >
                                </div>
                                <label class="col-sm-1 control-label">Valor S.T</label>
                                <div class="col-sm-3 col-md-2">
                                    <input id="icu_valorst" class="form-control" type="number" placeholder="Valor S.T" required >
                                </div>                                
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-1 col-md-offset-1 col-sm-1">
                                    <button type="submit" class="btn btn-primary" title="Agregar" id="icu_agregar">&nbsp;<span class="glyphicon glyphicon-floppy-disk"></span>&nbsp;</button>
                                </div>
                            </div>
                        </form>               
                        <br>
                        <br>
                        <table class="table table-striped display" id="icu_tabla">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Descripción</th>
                                    <th>Profesor</th>                                    
                                </tr>
                            </thead>
                            <tbody id="icu_tbody">
                                
                            </tbody>                                                                                       
                        </table>
                    </div>
                </div>
            </div>
        </div>        
        <?php include 'core/view/modal_clase_crear.php'?>
        <?php include 'core/inc/footer_index.php'?>
        <script src="/style/js/ingreso_cursos.js" type="text/javascript"></script>
    </body>
</html>
