<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        <?php include 'core/inc/header_admin.php' ?>
        <div class="container">
            <div class="row">
                <div class="panel panel-info">
                    <div class="panel-heading">Ingreso Canchas</div>
                    <div class="panel-body">
                        <form class="form-horizontal" action="" onsubmit="add_cancha(); return false">
                            <div class="form-group">                                
                                <label class="col-sm-2 col-md-1 control-label">Descripción</label>
                                <div class="col-sm-5 col-md-5">
                                    <input id="ic_descripcion" class="form-control" type="text" placeholder="Descripción" required>
                                </div>
                                <label class="col-sm-1 control-label">Apertura</label>
                                <div class="col-sm-3 col-md-2">
                                    <input id="ic_apertura" class="form-control" type="time" placeholder="Apertura" required >
                                </div>
                                <label class="col-sm-1 control-label">Cierre</label>
                                <div class="col-sm-3 col-md-2">
                                    <input id="ic_cierre" class="form-control" type="time" placeholder="Cierre" required >
                                </div>
                                
                            </div>
                            <div class="form-group">
                                <label class="col-sm-1 control-label">Valor S.A</label>
                                <div class="col-sm-3 col-md-2">
                                    <input id="ic_valorsa" class="form-control" type="number" placeholder="Valor S.A" required >
                                </div>
                                <label class="col-sm-1 control-label">Valor S.T</label>
                                <div class="col-sm-3 col-md-2">
                                    <input id="ic_valorst" class="form-control" type="number" placeholder="Valor S.T" required >
                                </div>
                                <div class="col-sm-1">
                                    <button type="submit" class="btn btn-primary" title="Agregar" id="ic_agregar">&nbsp;<span class="glyphicon glyphicon-floppy-disk"></span>&nbsp;</button>
                                </div>
                            </div>
                        </form>               
                        <br>
                        <br>
                        <table class="table table-striped display" id="ic_tabla">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Descripción</th>
                                    <th>Apertura</th>
                                    <th>Cierre</th>
                                    <th>Valor S.A</th>
                                    <th>Valor S.T</th>
                                </tr>
                            </thead>
                            <tbody id="ic_tbody">
                                
                            </tbody>                                                                                          
                        </table>
                    </div>
                </div>
            </div>
        </div>        
        <?php include 'core/inc/footer_index.php'?>
        <script src="/style/js/ingreso_canchas.js" type="text/javascript"></script>
    </body>
</html>
