<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        <?php include 'core/view/header_login.phtml'; ?>
        <div class="container-fluid">
            <div class="row">
                <br><br><br><br>
                <div class="col-xs-offset-1 col-xs-10 col-sm-offset-3 col-sm-6 col-md-offset-4 col-md-4">
                    <?php 
                    if((isset($_GET['m']))and($_GET['m'] == 1))
                    {
                        echo '<div class="alert alert-danger" role="alert"><p>Usuario o Contraseña incorrectos porfavor intenta denuevo</p></div>';
                    }
                    ?>
                    <form class="form-horizontal text-center" action="" method="post">
                        <div class="form-group">
                            <label for="exampleInputName2">Usuario</label>
                            <input type="text" class="form-control" name="rut" id="user_rut" placeholder="Rut" required>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail2">Contraseña</label>
                            <input type="password" class="form-control" name="pass" placeholder="Contraseña" required>
                        </div>                               
                        <div class="form-group">
                            <div>
                                <select class="form-control" id="sel_socio" name="sel_socio">
                                    <option value="1">Socio Activo</option>
                                    <option value="2">Socio Transeunte</option>
                                    <option value="3">Familiar Activo</option>
                                    <option value="4">Familiar Transeunte</option>                                    
                            </select>
                            </div>                                                               
                        </div>
                        <div class="form-group">                            
                            <button type="submit" value="si" name="grabar" class="btn btn-success">Iniciar</button>
                        </div>
                    </form>
                </div>
            </div>            
        </div>
        <?php include 'core/inc/footer_index.php'?>
        <script src="style/js/log_user.js" type="text/javascript"></script>
    </body>
</html>
