<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        <?php include 'core/inc/header_admin.php' ?>
        <link href="select2/dist/css/select2.min.css" rel="stylesheet">
        <div class="container">
            <div class="row">
                <div class="panel panel-info">
                    <div class="panel-heading">Pagar Cuota</div>
                    <div class="panel-body">
                        <form class="form-horizontal">
                            <div class="form-group">                     
                                <div class="col-sm-3 col-md-3">
                                    <select id="sel_cuota" class="js-example-basic-single js-states form-control">
                                        <option value="0">Seleccione Cuota</option>                                        
                                    </select>
                                </div>                                                                   
                            </div>                            
                        </form>               
                        <br>
                        <br>
                        <table class="table table-striped display" id="pcs_tabla">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Rut</th>                                    
                                    <th>Nombre</th>
                                    <th>Valor</th>
                                    <th>Estado</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody id="pcs_tbody">
                                
                            </tbody>                                                                                       
                        </table>
                    </div>
                </div>
            </div>
        </div>     
        <?php include 'core/view/modal_cuotas.php'?>
        <?php include 'core/inc/footer_index.php'?>
        <script src="select2/dist/js/select2.min.js"></script>
        <script src="/style/js/pago_cuota.js" type="text/javascript"></script>
    </body>
</html>
