<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        <?php include 'core/inc/header_user.php'; ?>
        <?php 
            echo $_SESSION['NOMBRE'].' - '.$_SESSION['EDAD'].' - '.$_SESSION['USUARIO'].' - '.$_SESSION['SOCIO'];
?>
        <?php include 'core/inc/footer_index.php'; ?>
    </body>
</html>
