<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        <?php include 'core/inc/header_admin.php' ?>
        <link href="select2/dist/css/select2.min.css" rel="stylesheet">
        <div class="container">
            <div class="row print-invi">
                <div class="panel panel-info">
                    <div class="panel-heading">Consultas</div>
                    <div class="panel-body">
                        <form class="form-horizontal">
                            <div class="form-group">                       
                                <div class="col-sm-3 col-md-3">
                                    <select id="consultas_principal" class="js-example-basic-single js-states form-control">
                                        <option value="0">Seleccione</option>
                                        <option value="1">Socio Activo</option>
                                        <option value="2">Socio transeunte</option>
                                        <option value="3">Competencias</option>
                                        <option value="4">Canchas</option>
                                        <option value="5">Cursos</option>
<!--                                        <option value="6">Club Social</option>-->
                                    </select>
                                </div>                            
                                <div class="col-sm-3 col-md-3">
                                    <select id="consultas_segundaria" class="js-example-basic-single js-states form-control invi">
                                        <option value="0">Seleccione</option>                                        
                                    </select>
                                </div>
                                <div id="fechas" class="invi">
                                    <label class="col-sm-1 control-label">Desde</label>
                                    <div class="col-sm-3 col-md-2">                                    
                                        <input id="fecha_ini" class="form-control" type="date" placeholder="DD/MM/AAAA" required>                                    
                                    </div>
                                    <label class="col-sm-1 control-label">Hasta</label>
                                    <div class="col-sm-3 col-md-2">                                    
                                        <input id="fecha_fin" class="form-control" type="date" placeholder="DD/MM/AAAA" required>
                                    </div>
                                </div>
                                <div id="consulta3" class="col-sm-3 col-md-3 invi">
                                    <select id="consultas_terciaria" class="js-example-basic-single js-states form-control invi">
                                        <option value="0">Seleccione</option>                                        
                                    </select>
                                </div> 
                            </div>                            
                        </form>
                    </div>
                </div>
            </div>
            <!--Fila para las tablas e impresión-->
            <div class="row">
                <div class="panel panel-info" id="panel-imprime">
                    <div class="panel-heading" id="panel_titulo"></div>
                    <div class="panel-body">
                        <div class="col-sm-offset-11 col-sm-1">
                            <button id="btn-imprime" type="button" class="btn btn-warning print-invi" title="">&nbsp;<span class="glyphicon glyphicon-print"></span>&nbsp;</button>
                        </div>
                        <table class="table table-striped display" id="reporte_tabla">
                            <thead id="reporte_thead">
                                
                            </thead>                                                                                                                       
                        </table>
                    </div>
                </div>
            </div>
        </div>        
        <?php include 'core/inc/footer_index.php'?>
        <script src="select2/dist/js/select2.min.js"></script>
        <script src="/style/js/reportes.js" type="text/javascript"></script>
    </body>
</html>
