<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        <?php include 'core/inc/header_admin.php' ?>
        <div class="container">
            <div class="row">
                <div class="panel panel-info">
                    <div class="panel-heading">Reserva Canchas</div>
                    <div class="panel-body">
                        <form class="form-horizontal">
                            <div class="form-group">
                                <div class="col-sm-1">
                                    <button type="button" class="btn btn-primary" title="Buscar" id="rc_buscar">&nbsp;<span class="glyphicon glyphicon-search"></span>&nbsp;</button>
                                </div>
                                <label class="col-sm-1 col-md-1 control-label">Socio</label>
                                <div class="col-sm-3 col-md-3">
                                    <input id="rc_rut" class="form-control" type="text" placeholder="Rut" required disabled>
                                </div>
                                <label class="col-sm-1 control-label">Nombres</label>
                                <div class="col-sm-6 col-md-6">
                                    <input id="rc_nombres" class="form-control" type="text" placeholder="Nombres" required disabled>
                                </div>                                                               
                            </div>
                            <div class="form-group">
                                <div class="col-xs-3 col-sm-1 col-md-1">
                                    <input id="rc_id" class="form-control" type="text" placeholder="ID" required disabled>
                                </div>
                                <div class="col-xs-9 col-sm-11 col-md-11">
                                    <input id="rc_descripcion" class="form-control" type="text" placeholder="Descripción" required disabled>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-xs-12 col-sm-3 col-md-3">
                                    <input id="rc_fecha" class="form-control" type="date" placeholder="dd/mm/aaaa" required>
                                </div>
                                
                            </div>
                        </form>                
                        <br>
                        <table class="table table-striped display" id="rc_thorario">
                            <thead>
                                <tr>
                                    <th>Periodo</th>
                                    <th>Horario</th>
                                    <th id="rc_tfecha">Estado</th>                                    
                                </tr>
                            </thead>
                            <tbody id="rc_htbody">
                                <tr class="fila_horario" style="cursor:pointer">
                                    <td>1</td>
                                    <td>07:00-07:59</td>                                    
                                    <td id="btn1" class="alert alert-success">Disponible</td>
                                </tr>
                                <tr class="fila_horario" style="cursor:pointer">
                                    <td>2</td>
                                    <td>08:00-08:59</td>                                    
                                    <td id="btn2" class="alert alert-success">Disponible</td>
                                </tr>
                                <tr class="fila_horario" style="cursor:pointer">
                                    <td>3</td>
                                    <td>09:00-09:59</td>
                                    <td id="btn3" class="alert alert-success">Disponible</td>
                                </tr>
                                <tr class="fila_horario" style="cursor:pointer">
                                    <td>4</td>
                                    <td>10:00-10:59</td>
                                    <td id="btn4" class="alert alert-success">Disponible</td>
                                </tr>
                                <tr class="fila_horario" style="cursor:pointer">
                                    <td>5</td>
                                    <td>11:00-11:59</td>
                                    <td id="btn5" class="alert alert-success">Disponible</td>
                                </tr>
                                <tr class="fila_horario" style="cursor:pointer">
                                    <td>6</td>
                                    <td>12:00-12:59</td>
                                    <td id="btn6" class="alert alert-success">Disponible</td>
                                </tr>
                                <tr class="fila_horario" style="cursor:pointer">
                                    <td>7</td>
                                    <td>13:00-13:59</td>
                                    <td id="btn7" class="alert alert-success">Disponible</td>
                                </tr>
                                <tr class="fila_horario" style="cursor:pointer">
                                    <td>8</td>
                                    <td>14:00-14:59</td>
                                    <td id="btn8" class="alert alert-success">Disponible</td>
                                </tr>
                                <tr class="fila_horario" style="cursor:pointer">
                                    <td>9</td>
                                    <td>15:00-15:59</td>
                                    <td id="btn9" class="alert alert-success">Disponible</td>
                                </tr>
                                <tr class="fila_horario" style="cursor:pointer">
                                    <td>10</td>
                                    <td>16:00-16:59</td>
                                    <td id="btn10" class="alert alert-success">Disponible</td>
                                </tr>
                                <tr class="fila_horario" style="cursor:pointer">
                                    <td>11</td>
                                    <td>17:00-17:59</td>
                                    <td id="btn11" class="alert alert-success">Disponible</td>
                                </tr>
                                <tr class="fila_horario" style="cursor:pointer">
                                    <td>12</td>
                                    <td>18:00-18:59</td>
                                    <td id="btn12" class="alert alert-success">Disponible</td>
                                </tr>
                                <tr class="fila_horario" style="cursor:pointer">
                                    <td>13</td>
                                    <td>19:00-19:59</td>
                                    <td id="btn13" class="alert alert-success">Disponible</td>
                                </tr>
                                <tr class="fila_horario" style="cursor:pointer">
                                    <td>14</td>
                                    <td>20:00-20:59</td>
                                    <td id="btn14" class="alert alert-success">Disponible</td>
                                </tr>
                                <tr class="fila_horario" style="cursor:pointer">
                                    <td>15</td>
                                    <td>21:00-21:59</td>
                                    <td id="btn15" class="alert alert-success">Disponible</td>
                                </tr>
                                <tr class="fila_horario" style="cursor:pointer">
                                    <td>16</td>
                                    <td>22:00-22:59</td>
                                    <td id="btn16" class="alert alert-success">Disponible</td>
                                </tr>
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>Periodo</th>
                                    <th>Horario</th>
                                    <th id="rc_fecha1">Estado</th>
                                                                                                 
                                </tr>
                            </tfoot>                                                               
                        </table>
                        <br>
                        <table class="table table-striped display" id="rc_tabla">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Descripción</th>
                                    <th>Apertura</th>
                                    <th>Cierre</th>
                                </tr>
                            </thead>
                            <tbody id="rc_tbody">
                                
                            </tbody>                                                                                         
                        </table>
                    </div>
                </div>
            </div>
        </div>        
        <?php include 'core/view/modal_buscar_socio.php'?>
        <?php include 'core/view/modal_reserva_cancha.php'?>
        <?php include 'core/inc/footer_index.php'?>
        <script src="/style/js/reserva_canchas.js" type="text/javascript"></script>
    </body>
</html>
