<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>       
        <div class="container">
            <br><br>
            <div class="row">
                <div class="panel panel-info">
                    <div class="panel-heading">Cerrar Sesión</div>
                    <div class="panel-body">
                        <form class="form-horizontal text-center" action="" method="post">
                            <div class="alert alert-success" role="alert"><p>La Sesión fue cerrada de forma exitosa!</p></div>                           
                        </form>              
                    </div>
                </div>
            </div>
        </div>        
        <?php include 'core/inc/footer_index.php'?>
        <script src="style/js/familiar_sa.js" type="text/javascript"></script>
    </body>
</html>
