<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        <?php include 'core/inc/header_user.php' ?>
        <div class="container">
            <div class="row">
                <div class="panel panel-info">
                    <div class="panel-heading">Clases</div>
                    <div class="panel-body">                        
                        <table class="table table-striped display" id="rc_tabla">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Curso</th>
                                    <th>Profesor</th>                                    
                                </tr>
                            </thead>
                            <tbody id="rc_tbody">
                                
                            </tbody>                                                                                       
                        </table>
                        <br>
                        <h4 id="titulo"></h4>
                        <br>
                        <table class="table table-striped display" id="rc_thorario">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Fecha</th>
                                    <th>inicio</th>
                                    <th>Termino</th>
                                    <th>Cupos</th>                                   
                                </tr>
                            </thead>
                            <tbody id="rc_htbody">
                                
                            </tbody>                                                                                         
                        </table>
                        <br>
                    </div>
                </div>
            </div>
        </div>      
        <?php include 'core/view/modal_participantes.php'?>
        <?php include 'core/inc/footer_index.php'?>
        <script src="/style/js/ureserva_clases.js" type="text/javascript"></script>
    </body>
</html>
