<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        <?php include 'core/inc/header_user.php' ?>
        <div class="container">
            <div class="row">
                <div class="panel panel-info">
                    <div class="panel-heading">Reserva Canchas</div>
                    <div class="panel-body">
                        <form class="form-horizontal">                            
                            <div class="form-group">
                                <div class="col-xs-12 col-sm-3 col-md-3">
                                    <input id="rc_fecha" class="form-control" type="date" value="<?php echo date("Y-m-d"); ?>" required>
                                </div>                                
                            </div>
                        </form>                
                        <br>
                        <table class="table table-striped display" id="rc_tabla">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Descripción</th>
                                    <th>Apertura</th>
                                    <th>Cierre</th>
                                </tr>
                            </thead>
                            <tbody id="rc_tbody">
                                
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>ID</th>
                                    <th>Descripción</th>
                                    <th>Apertura</th>
                                    <th>Cierre</th>                          
                                </tr>
                            </tfoot>                                                               
                        </table>
                        <br>
                        <table class="table table-striped display" id="rc_thorario">
                            <thead>
                                <tr>
                                    <th>Periodo</th>
                                    <th>Horario</th>
                                    <th id="rc_tfecha">Estado</th>                                    
                                </tr>
                            </thead>
                            <tbody id="rc_htbody">
                                
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>Periodo</th>
                                    <th>Horario</th>
                                    <th id="rc_fecha1">Estado</th>                                                                                                 
                                </tr>
                            </tfoot>                                                               
                        </table>                
                    </div>
                </div>
            </div>
        </div>       
        <?php include 'core/view/modal_participantes.php'?>
        <?php include 'core/inc/footer_index.php'?>
        <script src="/style/js/ureserva_canchas.js" type="text/javascript"></script>
    </body>
</html>
