<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        <?php include 'core/inc/header_user.php' ?>
        <div class="container">
            <div class="row">
                <div class="panel panel-info">
                    <div class="panel-heading">Reserva Canchas</div>
                    <div class="panel-body">                                     
                        <br>                        
                        <table class="table table-striped display" id="rc_tabla">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Descripción</th>
                                    <th>Cupos</th>                                
                                </tr>
                            </thead>
                            <tbody id="rc_tbody">
                                
                            </tbody>                                                                                          
                        </table>
                    </div>
                </div>
            </div>
        </div>                
        <?php include 'core/view/modal_participantes.php'?>
        <?php include 'core/inc/footer_index.php'?>
        <script src="/style/js/ureserva_competencias.js" type="text/javascript"></script>
    </body>
</html>
